---
- name: Add universe repo
  apt_repository: repo='deb http://archive.ubuntu.com/ubuntu {{ ansible_distribution_release }} universe' state=present
  when: ansible_distribution == "Ubuntu"

- name: Add ownCloud repo
  apt_repository: repo='deb http://download.opensuse.org/repositories/isv:/ownCloud:/community/xUbuntu_{{ ansible_distribution_version }}/ /' state=present update_cache=yes
  when: ansible_distribution == "Ubuntu" and ansible_distribution_major_version >= 12

- name: Add ownCloud repo key
  apt_key: url='http://download.opensuse.org/repositories/isv:ownCloud:community/xUbuntu_{{ ansible_distribution_version }}/Release.key' state=present
  when: ansible_distribution == "Ubuntu" and ansible_distribution_major_version >= 12

- name: Install dependencies
  apt: pkg={{ item }} state=present
  with_items:
    - php-xml-parser
    - php5-intl
    - php5-mcrypt
    - curl
    - exim4
    - php5-imagick
    - php-apc

- name: Install ownCloud
  apt: name=owncloud state=present force=yes

- name: Adjust Apache docroot
  replace: dest=/etc/apache2/sites-enabled/000-default.conf regexp='DocumentRoot /var/www/html' replace='DocumentRoot /var/www/owncloud'
  notify: reload apache